
CREATE DATABASE AdoptARandomDogDB;
GO

USE AdoptARandomDogDB;
GO

CREATE TABLE Dogs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    BirthDate DATE NOT NULL DEFAULT(GETDATE()),
    ImageUrl VARCHAR(255) NULL,
    Adopted BIT NOT NULL DEFAULT 0,
);
GO

CREATE TABLE Tutor (
Id INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Phone VARCHAR(11) NOT NULL,
Email VARCHAR(50) NOT NULL,
DogId INT NOT NULL
);
GO

ALTER TABLE Tutor
ADD FOREIGN KEY(DogId) REFERENCES [Dogs](Id)




SELECT * FROM Dogs
SELECT * FROM Tutor


